
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import webbrowser

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, messagebox, filedialog, Button, PhotoImage

from datetime import date
import pdfkit
from num2words import num2words

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)
def remp_date():
    today = date.today()
    entry_1.delete(0, 'end')
    entry_1.insert('end', today.strftime("%d/%m/%Y"))

def calculer(designations):
    for article in designations:
        article.append(article[0]*article[2])
    return designations

def somme(designations):
    summ = 0
    for article in designations:
        summ = summ + article[3]
    return summ

def facture(designations, num_fact, date, doit, num_article, rcn, idfiscal, nomfact):
    designations = calculer(designations)
    summ = somme(designations)
    sumstr = "{:,.2f}".format(summ)
    summ = num2words(summ, to='currency', lang='fr', cents=False).replace('euros', 'Dinars Algérien')
    htmldes = ""
    i = 1
    for article in designations:
        htmldes = htmldes + "<tr>"
        htmldes = htmldes + "<td>{:02d}</td>".format(i)
        htmldes = htmldes + f"<td>{article[1].capitalize()}</td>" 
        htmldes = htmldes + "<td>{:02d}</td>".format(article[0])
        htmldes = htmldes + "<td>{:,.2f}</td>".format(article[2])
        htmldes = htmldes + "<td>{:,.2f}</td>".format(article[3])
        htmldes = htmldes + "</tr>"
        i = i + 1

    htmlstr = """<!DOCTYPE html>
                    <html>
                        <head>
                            <meta charset="utf-8">
                            <title>Document</title>
                            <style type=text/css>
                                body{
                                    font-family: "Roboto";
                                }
                                .topleft { 
                                    float: left; 
                                } 
                                .topright { 
                                    float: right; 
                                } 
                                div{ 
                                    padding : 3%; 
                                } 
                                th, td {
                                    border-bottom: 1px solid black;
                                } 
                                h1{
                                    text-align: center;
                                }
                                .tableheader{ 
                                    text-align: center; 
                                }
                            </style>""" + f"""
                        </head>
                            <body>
                            <div class="top">
                                <div class="topright">
                                    <p>Facture №: {num_fact}</p>
                                    <p>A: Khenchela le: {date}</p>
                                    <p>Doit: {doit.title()}</p>
                                </div>
                                <div></div>
                                <div></div>
                                <div></div>
                                <div class="topleft">
                                    <p>R.C.№: {rcn}</p>
                                    <p>ID Fiscal: {idfiscal}</p>
                                    <p>№ Article: {num_article}</p>
                                </div> 
                            </div>
                            <div></div>
                            <div></div>
                            <div></div>
                            <div class="titre">
                                <h1>Facture<h1>
                            </div>
                            <div class="tableau">
                                <table>
                                    <col width="30px"/>
                                    <col width="560px"/>
                                    <col width="40px"/>                                    
                                    <col width="100px"/>
                                    <col width="100px"/>
                                    <tr class="tableheader">                                        
                                        <th>№</th>
                                        <th>Designation</th>
                                        <th>Qte</th>
                                        <th>Prix Unitaire</th>
                                        <th>Montant</th>
                                    </tr>{htmldes}
                                    <tr>
                                        <td style="border-bottom: 1px white"></td>
                                        <td style="border-bottom: 1px white"></td>
                                        <td style="border-bottom: 1px white"></td>
                                        <td><b>Total</b></td>
                                        <td><b>{sumstr}</b></td>
                                </table> 
                            </div>
                            <div class="somme">
                                <p>Arrêté la facture à la somme de: {summ}.</p>
                            </div>
                        </body>
                    </html>"""
    pdfkit.from_string(htmlstr, f"{nomfact}") 

window = Tk()

window.geometry("410x610")
window.configure(bg = "#8E9CC0")


canvas = Canvas(
    window,
    bg = "#8E9CC0",
    height = 610,
    width = 410,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    12.0,
    6.0,
    anchor="nw",
    text="Date:",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    103.0,
    37.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_1.place(
    x=17.0,
    y=22.0,
    width=172.0,
    height=28.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: remp_date(),
    relief="flat"
)
button_1.place(
    x=214.0,
    y=22.0,
    width=100.0,
    height=30.0
)

canvas.create_text(
    12.0,
    54.0,
    anchor="nw",
    text="Facture №:",
    fill="#000000",
    font=("Roboto", 14 * -1))

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    103.0,
    85.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_2.place(
    x=17.0,
    y=70.0,
    width=172.0,
    height=28.0
)

canvas.create_text(
    214.0,
    54.0,
    anchor="nw",
    text="№ Article:",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    305.5,
    85.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_3.place(
    x=219.0,
    y=70.0,
    width=173.0,
    height=28.0
)

canvas.create_text(
    12.0,
    102.0,
    anchor="nw",
    text="Doit:",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    204.5,
    133.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_4.place(
    x=17.0,
    y=118.0,
    width=375.0,
    height=28.0
)

canvas.create_text(
    12.0,
    150.0,
    anchor="nw",
    text="R.C.№:",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    103.0,
    181.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_5.place(
    x=17.0,
    y=166.0,
    width=172.0,
    height=28.0
)

canvas.create_text(
    214.0,
    150.0,
    anchor="nw",
    text="ID Fiscal:",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_6 = PhotoImage(
    file=relative_to_assets("entry_6.png"))
entry_bg_6 = canvas.create_image(
    305.5,
    181.0,
    image=entry_image_6
)
entry_6 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
entry_6.place(
    x=219.0,
    y=166.0,
    width=173.0,
    height=28.0
)

canvas.create_text(
    16.0,
    198.0,
    anchor="nw",
    text="Qte",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

canvas.create_text(
    143.0,
    198.0,
    anchor="nw",
    text="Designation",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

canvas.create_text(
    321.0,
    198.0,
    anchor="nw",
    text="Prix Unitaire",
    fill="#000000",
    font=("Roboto", 14 * -1)
)

entry_image_7 = PhotoImage(
    file=relative_to_assets("entry_7.png"))
entry_bg_7 = canvas.create_image(
    27.0,
    229.0,
    image=entry_image_7
)
qt1 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt1.place(
    x=17.0,
    y=214.0,
    width=20.0,
    height=28.0
)

entry_image_8 = PhotoImage(
    file=relative_to_assets("entry_8.png"))
entry_bg_8 = canvas.create_image(
    181.0,
    229.0,
    image=entry_image_8
)
des1 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des1.place(
    x=50.0,
    y=214.0,
    width=262.0,
    height=28.0
)

entry_image_9 = PhotoImage(
    file=relative_to_assets("entry_9.png"))
entry_bg_9 = canvas.create_image(
    359.0,
    229.0,
    image=entry_image_9
)
prix1 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix1.place(
    x=326.0,
    y=214.0,
    width=66.0,
    height=28.0
)

entry_image_10 = PhotoImage(
    file=relative_to_assets("entry_10.png"))
entry_bg_10 = canvas.create_image(
    27.0,
    265.0,
    image=entry_image_10
)
qt2 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt2.place(
    x=17.0,
    y=250.0,
    width=20.0,
    height=28.0
)

entry_image_11 = PhotoImage(
    file=relative_to_assets("entry_11.png"))
entry_bg_11 = canvas.create_image(
    181.0,
    265.0,
    image=entry_image_11
)
des2 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des2.place(
    x=50.0,
    y=250.0,
    width=262.0,
    height=28.0
)

entry_image_12 = PhotoImage(
    file=relative_to_assets("entry_12.png"))
entry_bg_12 = canvas.create_image(
    359.0,
    265.0,
    image=entry_image_12
)
prix2 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix2.place(
    x=326.0,
    y=250.0,
    width=66.0,
    height=28.0
)

entry_image_13 = PhotoImage(
    file=relative_to_assets("entry_13.png"))
entry_bg_13 = canvas.create_image(
    27.0,
    301.0,
    image=entry_image_13
)
qt3 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt3.place(
    x=17.0,
    y=286.0,
    width=20.0,
    height=28.0
)

entry_image_14 = PhotoImage(
    file=relative_to_assets("entry_14.png"))
entry_bg_14 = canvas.create_image(
    181.0,
    301.0,
    image=entry_image_14
)
des3 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des3.place(
    x=50.0,
    y=286.0,
    width=262.0,
    height=28.0
)

entry_image_15 = PhotoImage(
    file=relative_to_assets("entry_15.png"))
entry_bg_15 = canvas.create_image(
    359.0,
    301.0,
    image=entry_image_15
)
prix3 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix3.place(
    x=326.0,
    y=286.0,
    width=66.0,
    height=28.0
)

entry_image_16 = PhotoImage(
    file=relative_to_assets("entry_16.png"))
entry_bg_16 = canvas.create_image(
    27.0,
    337.0,
    image=entry_image_16
)
qt4 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt4.place(
    x=17.0,
    y=322.0,
    width=20.0,
    height=28.0
)

entry_image_17 = PhotoImage(
    file=relative_to_assets("entry_17.png"))
entry_bg_17 = canvas.create_image(
    181.0,
    337.0,
    image=entry_image_17
)
des4 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des4.place(
    x=50.0,
    y=322.0,
    width=262.0,
    height=28.0
)

entry_image_18 = PhotoImage(
    file=relative_to_assets("entry_18.png"))
entry_bg_18 = canvas.create_image(
    359.0,
    337.0,
    image=entry_image_18
)
prix4 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix4.place(
    x=326.0,
    y=322.0,
    width=66.0,
    height=28.0
)

entry_image_19 = PhotoImage(
    file=relative_to_assets("entry_19.png"))
entry_bg_19 = canvas.create_image(
    27.0,
    373.0,
    image=entry_image_19
)
qt5 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt5.place(
    x=17.0,
    y=358.0,
    width=20.0,
    height=28.0
)

entry_image_20 = PhotoImage(
    file=relative_to_assets("entry_20.png"))
entry_bg_20 = canvas.create_image(
    181.0,
    373.0,
    image=entry_image_20
)
des5 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des5.place(
    x=50.0,
    y=358.0,
    width=262.0,
    height=28.0
)

entry_image_21 = PhotoImage(
    file=relative_to_assets("entry_21.png"))
entry_bg_21 = canvas.create_image(
    359.0,
    373.0,
    image=entry_image_21
)
prix5 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix5.place(
    x=326.0,
    y=358.0,
    width=66.0,
    height=28.0
)

entry_image_22 = PhotoImage(
    file=relative_to_assets("entry_22.png"))
entry_bg_22 = canvas.create_image(
    27.0,
    409.0,
    image=entry_image_22
)
qt6 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt6.place(
    x=17.0,
    y=394.0,
    width=20.0,
    height=28.0
)

entry_image_23 = PhotoImage(
    file=relative_to_assets("entry_23.png"))
entry_bg_23 = canvas.create_image(
    181.0,
    409.0,
    image=entry_image_23
)
des6 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des6.place(
    x=50.0,
    y=394.0,
    width=262.0,
    height=28.0
)

entry_image_24 = PhotoImage(
    file=relative_to_assets("entry_24.png"))
entry_bg_24 = canvas.create_image(
    359.0,
    409.0,
    image=entry_image_24
)
prix6 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix6.place(
    x=326.0,
    y=394.0,
    width=66.0,
    height=28.0
)

entry_image_25 = PhotoImage(
    file=relative_to_assets("entry_25.png"))
entry_bg_25 = canvas.create_image(
    27.0,
    445.0,
    image=entry_image_25
)
qt7 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt7.place(
    x=17.0,
    y=430.0,
    width=20.0,
    height=28.0
)

entry_image_26 = PhotoImage(
    file=relative_to_assets("entry_26.png"))
entry_bg_26 = canvas.create_image(
    181.0,
    445.0,
    image=entry_image_26
)
des7 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des7.place(
    x=50.0,
    y=430.0,
    width=262.0,
    height=28.0
)

entry_image_27 = PhotoImage(
    file=relative_to_assets("entry_27.png"))
entry_bg_27 = canvas.create_image(
    359.0,
    445.0,
    image=entry_image_27
)
prix7 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix7.place(
    x=326.0,
    y=430.0,
    width=66.0,
    height=28.0
)

entry_image_28 = PhotoImage(
    file=relative_to_assets("entry_28.png"))
entry_bg_28 = canvas.create_image(
    27.0,
    481.0,
    image=entry_image_28
)
qt8 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt8.place(
    x=17.0,
    y=466.0,
    width=20.0,
    height=28.0
)

entry_image_29 = PhotoImage(
    file=relative_to_assets("entry_29.png"))
entry_bg_29 = canvas.create_image(
    181.0,
    481.0,
    image=entry_image_29
)
des8 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des8.place(
    x=50.0,
    y=466.0,
    width=262.0,
    height=28.0
)

entry_image_30 = PhotoImage(
    file=relative_to_assets("entry_30.png"))
entry_bg_30 = canvas.create_image(
    359.0,
    481.0,
    image=entry_image_30
)
prix8 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix8.place(
    x=326.0,
    y=466.0,
    width=66.0,
    height=28.0
)

entry_image_31 = PhotoImage(
    file=relative_to_assets("entry_31.png"))
entry_bg_31 = canvas.create_image(
    27.0,
    517.0,
    image=entry_image_31
)
qt9 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt9.place(
    x=17.0,
    y=502.0,
    width=20.0,
    height=28.0
)

entry_image_32 = PhotoImage(
    file=relative_to_assets("entry_32.png"))
entry_bg_32 = canvas.create_image(
    181.0,
    517.0,
    image=entry_image_32
)
des9 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des9.place(
    x=50.0,
    y=502.0,
    width=262.0,
    height=28.0
)

entry_image_33 = PhotoImage(
    file=relative_to_assets("entry_33.png"))
entry_bg_33 = canvas.create_image(
    359.0,
    517.0,
    image=entry_image_33
)
prix9 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix9.place(
    x=326.0,
    y=502.0,
    width=66.0,
    height=28.0
)

entry_image_34 = PhotoImage(
    file=relative_to_assets("entry_34.png"))
entry_bg_34 = canvas.create_image(
    27.0,
    553.0,
    image=entry_image_34
)
qt10 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
qt10.place(
    x=17.0,
    y=538.0,
    width=20.0,
    height=28.0
)

entry_image_35 = PhotoImage(
    file=relative_to_assets("entry_35.png"))
entry_bg_35 = canvas.create_image(
    181.0,
    553.0,
    image=entry_image_35
)
des10 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
des10.place(
    x=50.0,
    y=538.0,
    width=262.0,
    height=28.0
)

entry_image_36 = PhotoImage(
    file=relative_to_assets("entry_36.png"))
entry_bg_36 = canvas.create_image(
    359.0,
    553.0,
    image=entry_image_36
)
prix10 = Entry(
    bd=0,
    bg="#C4C4C4",
    highlightthickness=0
)
prix10.place(
    x=326.0,
    y=538.0,
    width=66.0,
    height=28.0
)


def get_articles():
    articles = []
    des_array = [des1, des2, des3, des4, des5, des6, des7, des8, des9, des10]
    qt_array = [qt1, qt2, qt3, qt4, qt5, qt6, qt7, qt8, qt9, qt10]
    prix_array = [prix1, prix2, prix3, prix4, prix5, prix6, prix7, prix8, prix9, prix10]
    verifier = True
    for des in des_array:
        if len(des.get()) > 0:
            try:
                int(qt_array[des_array.index(des)].get())
                try:
                    float(prix_array[des_array.index(des)].get())
                    articles.append([int(qt_array[des_array.index(des)].get()), des.get(), float(prix_array[des_array.index(des)].get())])
                except:
                    verifier = False
            except:
                verifier = False
    
    if verifier == True:
        return articles
    else:
        return verifier

def imprimer():
    articles = get_articles()
    if articles == False:
        messagebox.showinfo("Erreur", "Verifier les entrées.")
    else:
        filename = entry_2.get().replace("/", "-")
        filename = filedialog.asksaveasfile(filetypes = [("PDF", "*.pdf")], defaultextension = [("PDF", "*.pdf")], initialfile = f"Facture {filename}")
        try:
            facture(articles, entry_2.get(), entry_1.get(), entry_4.get(), entry_3.get(), entry_5.get(), entry_6.get(), filename.name)
            webbrowser.open(filename.name)
        except:
            messagebox.showinfo("Erreur", "Verifier les entrées.")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: imprimer(),
    relief="flat"
)
button_2.place(
    x=217.0,
    y=574.0,
    width=100.0,
    height=30.0
)
window.resizable(False, False)
window.mainloop()


